version: '3.4'

services:
  californianhealthblazor:
    container_name: californianhealthblazor
    image: ${DOCKER_REGISTRY-}californianhealthblazor
    build:
      context: .
      dockerfile: Web/CalifornianHealthBlazor/Dockerfile
    ports:
      - "32773:443"
      - "32774:80"
    depends_on:
      - calendar
      - appointmentbooking

  calendar:
    container_name: calendar
    image: ${DOCKER_REGISTRY-}calendar
    build:
      context: .
      dockerfile: Services/Calendar/Dockerfile
    ports:
      - "32771:443"
      - "32772:80"
    depends_on:
      - sqlserver
    restart: on-failure:5

  appointmentbooking:
    container_name: appointmentbooking
    image: ${DOCKER_REGISTRY-}appointmentbooking
    build:
      context: .
      dockerfile: Services/AppointmentBooking/Dockerfile
    ports:
      - "32769:443"
      - "32770:80"
    restart: on-failure:5

  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Test1234678!"
      ACCEPT_EULA: "Y"
    ports:
      - "5434:1433"
    volumes: 
      - "sqlserver-data:/var/opt/sqlserver"
      - "sqlserver-data:/var/opt/mssql"

  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "Test1234!"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"

  elasticsearch:
   container_name: elasticsearch
   image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
   ports:
    - 9200:9200
   volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
   environment:
    - xpack.monitoring.enabled=true
    - xpack.watcher.enabled=false
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node

  kibana:
   container_name: kibana
   image: docker.elastic.co/kibana/kibana:7.6.2
   ports:
    - 5601:5601
   depends_on:
    - elasticsearch
   environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200

volumes:
  elasticsearch-data:
  sqlserver-data: