version: '3.4'

services:
  californianhealthblazor:
    image: ${DOCKER_REGISTRY-}californianhealthblazor
    build:
      context: .
      dockerfile: Web/CalifornianHealthBlazor/Dockerfile
    ports:
      - "32773:443"
      - "32774:80"
    depends_on:
        - calendar
        - appointmentbooking

  calendar:
    image: ${DOCKER_REGISTRY-}calendar
    build:
      context: .
      dockerfile: Services/Calendar/Dockerfile
    ports:
      - "32771:443"
      - "32772:80"
    restart: on-failure:5

  appointmentbooking:
    image: ${DOCKER_REGISTRY-}appointmentbooking
    build:
      context: .
      dockerfile: Services/AppointmentBooking/Dockerfile
    ports:
      - "32769:443"
      - "32770:80"
    restart: on-failure:5

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: "sqlserver"
    environment:
      - SA_PASSWORD=Test1234678!
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "Test1234!"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"